require 'soap/default.rb'
require 'soap/defaultMappingRegistry'

require 'soap/rpc/driver'

class SOAPServerPort < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "http://localhost:8000/SOAP"
  NsAuraUserData = "urn:auraUserData"

  Methods = [
    [ XSD::QName.new(NsAuraUserData, "askQuestion"),
      "askQuestion",
      "askQuestion",
      [ ["in", "question", ["::SOAP::SOAPString"]],
        ["in", "forceWord", ["::SOAP::SOAPString"]],
        ["in", "pos", ["::SOAP::SOAPQName"]],
        ["in", "uofm", ["::SOAP::SOAPBoolean"]],
        ["retval", "conceptMap", ["QuestionConceptMap", "urn:auraUserData", "QuestionConceptMap"]],
        ["out", "errors", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "whyNot"),
      "whyNot",
      "whyNot",
      [ ["in", "concept", ["::SOAP::SOAPQName"]],
        ["retval", "viewpoint", ["Viewpoint", "urn:auraUserData", "Viewpoint"]],
        ["out", "setupMatched", ["QNameArray", "urn:auraUserData", "QNameArray"]],
        ["out", "setupNotMatched", ["QNameArray", "urn:auraUserData", "QNameArray"]],
        ["out", "conceptMatched", ["QNameArray", "urn:auraUserData", "QNameArray"]],
        ["out", "conceptNotMatched", ["QNameArray", "urn:auraUserData", "QNameArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "pingServer"),
      "pingServer",
      "pingServer",
      [ ["in", "dummy", ["::SOAP::SOAPString"]],
        ["retval", "dummy", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "changeRelation"),
      "changeRelation",
      "changeRelation",
      [ ["in", "rootIndividual", ["::SOAP::SOAPQName"]],
        ["in", "edges", ["ArrayOfGAFs", "urn:auraUserData", "ArrayOfGAFs"]],
        ["in", "relation", ["::SOAP::SOAPQName"]],
        ["retval", "conceptMap", ["QuestionConceptMap", "urn:auraUserData", "QuestionConceptMap"]],
        ["out", "errors", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getNonVisibleClasses"),
      "getNonVisibleClasses",
      "getNonVisibleClasses",
      [ ["in", "dummy", ["::SOAP::SOAPString"]],
        ["retval", "classes", ["QNameArray", "urn:auraUserData", "QNameArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "deleteSmeConcept"),
      "deleteSmeConcept",
      "deleteSmeConcept",
      [ ["in", "concept", ["::SOAP::SOAPQName"]],
        ["retval", "reviewList", ["QNameArray", "urn:auraUserData", "QNameArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "stemString"),
      "stemString",
      "stemString",
      [ ["in", "inputString", ["::SOAP::SOAPString"]],
        ["retval", "outputString", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "checkpointSuccess"),
      "checkpointSuccess",
      "checkpointSuccess",
      [ ["in", "idCreated", ["::SOAP::SOAPInt"]],
        ["retval", "dummy", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "genericSearch"),
      "genericSearch",
      "genericSearch",
      [ ["in", "inputs", ["StringArray", "urn:auraUserData", "StringArray"]],
        ["retval", "termResultList", ["ArrayOfTermResult", "urn:auraUserData", "ArrayOfTermResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "createCompound"),
      "createCompound",
      "createCompound",
      [ ["in", "compound", ["Formula", "urn:auraUserData", "Formula"]],
        ["in", "className", ["::SOAP::SOAPQName"]],
        ["retval", "compoundClass", ["::SOAP::SOAPQName"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getClassRelatedClasses"),
      "getClassRelatedClasses",
      "getClassRelatedClasses",
      [ ["in", "class", ["::SOAP::SOAPString"]],
        ["retval", "classes", ["QNameArray", "urn:auraUserData", "QNameArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "answerCorrect"),
      "answerCorrect",
      "answerCorrect",
      [ ["in", "id", ["::SOAP::SOAPString"]],
        ["retval", "dummy", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "initialize"),
      "initialize",
      "initialize",
      [ ["in", "pingInterval", ["::SOAP::SOAPInt"]],
        ["in", "checkpointInterval", ["::SOAP::SOAPInt"]],
        ["retval", "idToRecover", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getValidPropertyValues"),
      "getValidPropertyValues",
      "getValidPropertyValues",
      [ ["in", "individual", ["::SOAP::SOAPQName"]],
        ["retval", "relationsArray", ["ValidValuesArray", "urn:auraUserData", "ValidValuesArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "shakenFaultExporter"),
      "shakenFaultExporter",
      "shakenFaultExporter",
      [ ["in", "SOAPServerPart", [nil, "urn:auraUserData", "dummy"]],
        ["retval", "concept", ["::SOAP::SOAPQName"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getDebugNames"),
      "getDebugNames",
      "getDebugNames",
      [ ["in", "dummy", ["::SOAP::SOAPString"]],
        ["retval", "viewpoints", ["ArrayOfViewpoints", "urn:auraUserData", "ArrayOfViewpoints"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getViewpointInfo"),
      "getViewpointInfo",
      "getViewpointInfo",
      [ ["in", "viewpoint", ["::SOAP::SOAPQName"]],
        ["retval", "viewpoint", ["Viewpoint", "urn:auraUserData", "Viewpoint"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getAsynchronousCallStatus"),
      "getAsynchronousCallStatus",
      "getAsynchronousCallStatus",
      [ ["in", "callName", ["::SOAP::SOAPQName"]],
        ["retval", "currentStage", ["::SOAP::SOAPInt"]],
        ["out", "maxStage", ["::SOAP::SOAPInt"]],
        ["out", "positionInStage", ["::SOAP::SOAPInt"]],
        ["out", "maxInStage", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getClassesUsedInLastQuestion"),
      "getClassesUsedInLastQuestion",
      "getClassesUsedInLastQuestion",
      [ ["in", "dummy", ["::SOAP::SOAPString"]],
        ["retval", "classes", ["QNameArray", "urn:auraUserData", "QNameArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "drilldownExplanation"),
      "drilldownExplanation",
      "drilldownExplanation",
      [ ["in", "function", ["::SOAP::SOAPString"]],
        ["in", "arguments", ["StringArray", "urn:auraUserData", "StringArray"]],
        ["retval", "explanation", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getRelationOptions"),
      "getWordSenses",
      "getRelationOptions",
      [ ["in", "source", ["::SOAP::SOAPQName"]],
        ["in", "relation", ["::SOAP::SOAPQName"]],
        ["in", "target", ["::SOAP::SOAPQName"]],
        ["retval", "options", ["ArrayOfRelationOptions", "urn:auraUserData", "ArrayOfRelationOptions"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "callLMapFunction"),
      "callLMapFunction",
      "callLMapFunction",
      [ ["in", "rootIndividual", ["::SOAP::SOAPQName"]],
        ["in", "action", ["::SOAP::SOAPQName"]],
        ["in", "arguments", ["LMapArgumentTable", "urn:auraUserData", "LMapArgumentTable"]],
        ["in", "uiAttributes", ["UIAttributeArray", "urn:auraUserData", "UIAttributeArray"]],
        ["retval", "conceptMap", ["ConceptMap", "urn:auraUserData", "ConceptMap"]],
        ["out", "conceptList", ["QNameArray", "urn:auraUserData", "QNameArray"]],
        ["out", "cmapList", ["QNameArray", "urn:auraUserData", "QNameArray"]],
        ["out", "conceptEditSummary", ["ConceptMapEditSummary", "urn:auraUserData", "ConceptMapEditSummary"]],
        ["out", "dummy", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getQuestions"),
      "getQuestions",
      "getQuestions",
      [ ["in", "inputText", ["::SOAP::SOAPString"]],
        ["in", "section", ["::SOAP::SOAPString"]],
        ["retval", "questions", ["StringArray", "urn:auraUserData", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getWordSenses"),
      "getWordSenses",
      "getWordSenses",
      [ ["in", "instance", ["::SOAP::SOAPQName"]],
        ["retval", "senses", ["ArrayOfWordSenses", "urn:auraUserData", "ArrayOfWordSenses"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "answerQuestion"),
      "answerQuestion",
      "answerQuestion",
      [ ["in", "questionID", ["::SOAP::SOAPString"]],
        ["retval", "answer", ["::SOAP::SOAPString"]],
        ["out", "canContinue", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "initializeComplete"),
      "initializeComplete",
      "initializeComplete",
      [ ["in", "idRecovered", ["::SOAP::SOAPInt"]],
        ["in", "isSuccess", ["::SOAP::SOAPBoolean"]],
        ["retval", "idToRecover", ["::SOAP::SOAPInt"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "changeWordSense"),
      "changeWordSense",
      "changeWordSense",
      [ ["in", "instance", ["::SOAP::SOAPQName"]],
        ["in", "sense", ["::SOAP::SOAPQName"]],
        ["retval", "conceptMap", ["QuestionConceptMap", "urn:auraUserData", "QuestionConceptMap"]],
        ["out", "errors", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getValidRelations"),
      "getValidRelations",
      "getValidRelations",
      [ ["in", "source", ["::SOAP::SOAPQName"]],
        ["in", "target", ["::SOAP::SOAPQName"]],
        ["retval", "SOAPServerPart002", [nil, "urn:auraUserData", "relationsArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getStructuredQuestions"),
      "getStructuredQuestions",
      "getStructuredQuestions",
      [ ["in", "inputText", ["::SOAP::SOAPString"]],
        ["in", "section", ["::SOAP::SOAPString"]],
        ["retval", "structuredQuestions", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "driCreateSelection"),
      "driCreateSelection",
      "driCreateSelection",
      [ ["in", "selectionType", ["::SOAP::SOAPQName"]],
        ["in", "selectionPath", ["::SOAP::SOAPString"]],
        ["in", "selectionURI", ["::SOAP::SOAPAnyURI"]],
        ["in", "selectionRangeStart", ["::SOAP::SOAPInt"]],
        ["in", "selectionRangeEnd", ["::SOAP::SOAPInt"]],
        ["in", "selectionName", ["::SOAP::SOAPQName"]],
        ["in", "selectionSummary", ["::SOAP::SOAPString"]],
        ["retval", "driCreateSelectionDisposition", ["::SOAP::SOAPQName"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "findPartitionsForClass"),
      "findPartitionsForClass",
      "findPartitionsForClass",
      [ ["in", "class", ["::SOAP::SOAPQName"]],
        ["retval", "partitions", ["PartitionsArray", "urn:auraUserData", "PartitionsArray"]],
        ["out", "edits", ["PartitionEditsArray", "urn:auraUserData", "PartitionEditsArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "blockDirtParaphrase"),
      "blockDirtParaphrase",
      "blockDirtParaphrase",
      [ ["in", "dirtParaphrase", ["::SOAP::SOAPString"]],
        ["retval", "dummy", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getDebugInfo"),
      "getDebugInfo",
      "getDebugInfo",
      [ ["in", "dummy", ["::SOAP::SOAPString"]],
        ["retval", "viewpoints", ["ArrayOfViewpoints", "urn:auraUserData", "ArrayOfViewpoints"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "continueAnswerQuestion"),
      "continueAnswerQuestion",
      "continueAnswerQuestion",
      [ ["in", "dummy", ["::SOAP::SOAPString"]],
        ["retval", "answer", ["::SOAP::SOAPString"]],
        ["out", "canContinue", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "abortAsynchronousCall"),
      "abortAsynchronousCall",
      "abortAsynchronousCall",
      [ ["in", "callName", ["::SOAP::SOAPQName"]],
        ["retval", "dummy", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "shutdown"),
      "shutdown",
      "shutdown",
      [ ["in", "errorStatus", ["::SOAP::SOAPInt"]],
        ["retval", "dummy", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getSmeDefinedConcepts"),
      "getSmeDefinedConcepts",
      "getSmeDefinedConcepts",
      [ ["in", "root", ["::SOAP::SOAPQName"]],
        ["retval", "clibConcepts", ["QNameArray", "urn:auraUserData", "QNameArray"]],
        ["out", "newConcepts", ["QNameArray", "urn:auraUserData", "QNameArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getExampleCPLSentences"),
      "getExampleCPLSentences",
      "getExampleCPLSentences",
      [ ["in", "dummy", ["::SOAP::SOAPString"]],
        ["retval", "sentences", ["StringArray", "urn:auraUserData", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "createNewClass"),
      "createNewClass",
      "createNewClass",
      [ ["in", "concept", ["::SOAP::SOAPQName"]],
        ["in", "conceptList", ["QNameArray", "urn:auraUserData", "QNameArray"]],
        ["retval", "concept", ["::SOAP::SOAPQName"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getClassSynonyms"),
      "getClassSynonyms",
      "getClassSynonyms",
      [ ["in", "concept", ["::SOAP::SOAPQName"]],
        ["retval", "vocabulary", ["VocabularyArray", "urn:auraUserData", "VocabularyArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "assertAsEqual"),
      "assertAsEqual",
      "assertAsEqual",
      [ ["in", "instance1", ["::SOAP::SOAPQName"]],
        ["in", "instance2", ["::SOAP::SOAPQName"]],
        ["retval", "conceptMap", ["QuestionConceptMap", "urn:auraUserData", "QuestionConceptMap"]],
        ["out", "errors", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "startQASession"),
      "startQASession",
      "startQASession",
      [ ["in", "dummy", ["::SOAP::SOAPString"]],
        ["retval", "dummy", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getMostGeneralInstanceClasses"),
      "getMostGeneralInstanceClasses",
      "getMostGeneralInstanceClasses",
      [ ["in", "individual", ["::SOAP::SOAPQName"]],
        ["in", "classBeingEdited", ["::SOAP::SOAPQName"]],
        ["retval", "classes", ["QNameArray", "urn:auraUserData", "QNameArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "auraFaultExporter"),
      "auraFaultExporter",
      "auraFaultExporter",
      [ ["in", "SOAPServerPart003", [nil, "urn:auraUserData", "dummy2"]],
        ["retval", "concept", ["::SOAP::SOAPQName"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getVocabulary"),
      "getVocabulary",
      "getVocabulary",
      [ ["in", "pattern", ["::SOAP::SOAPString"]],
        ["retval", "vocabulary", ["VocabularyArray", "urn:auraUserData", "VocabularyArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "driGetSelection"),
      "driGetSelection",
      "driGetSelection",
      [ ["in", "selectionURI", ["::SOAP::SOAPAnyURI"]],
        ["in", "selectionPath", ["::SOAP::SOAPString"]],
        ["in", "selectionRangeStart", ["::SOAP::SOAPInt"]],
        ["in", "selectionRangeEnd", ["::SOAP::SOAPInt"]],
        ["retval", "driGetSelectionDisposition", ["DocumentSelectionArray", "urn:auraUserData", "DocumentSelectionArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "answerQuestionIpad"),
      "answerQuestionIpad",
      "answerQuestionIpad",
      [ ["in", "questionID", ["::SOAP::SOAPString"]],
        ["retval", "answer", ["::SOAP::SOAPString"]],
        ["out", "canContinue", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getAllPartitions"),
      "getAllPartitions",
      "getAllPartitions",
      [ ["in", "classes", ["QNameArray", "urn:auraUserData", "QNameArray"]],
        ["retval", "partitions", ["PartitionsArray", "urn:auraUserData", "PartitionsArray"]],
        ["out", "edits", ["PartitionEditsArray", "urn:auraUserData", "PartitionEditsArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "createChemicalReaction"),
      "createChemicalReaction",
      "createChemicalReaction",
      [ ["in", "reaction", ["Reaction", "urn:auraUserData", "Reaction"]],
        ["in", "className", ["::SOAP::SOAPQName"]],
        ["in", "balance", ["::SOAP::SOAPBoolean"]],
        ["retval", "reactionClass", ["::SOAP::SOAPQName"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "commitEdits"),
      "commitEdits",
      "commitEdits",
      [ ["in", "dummy", ["::SOAP::SOAPString"]],
        ["retval", "dummy", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "driRemoveSelection"),
      "driRemoveSelection",
      "driRemoveSelection",
      [ ["in", "selectionURI", ["::SOAP::SOAPAnyURI"]],
        ["in", "selectionPath", ["::SOAP::SOAPString"]],
        ["in", "selectionRangeStart", ["::SOAP::SOAPInt"]],
        ["in", "selectionRangeEnd", ["::SOAP::SOAPInt"]],
        ["retval", "driRemoveSelectionDisposition", ["DocumentSelectionArray", "urn:auraUserData", "DocumentSelectionArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getClassDocumentation"),
      "getClassDocumentation",
      "getClassDocumentation",
      [ ["in", "concept", ["::SOAP::SOAPQName"]],
        ["in", "type", ["::SOAP::SOAPQName"]],
        ["retval", "documentation", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "prepareIndividual"),
      "prepareIndividual",
      "prepareIndividual",
      [ ["in", "concept", ["::SOAP::SOAPQName"]],
        ["retval", "concept", ["::SOAP::SOAPQName"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "exportOWL"),
      "exportOWL",
      "exportOWL",
      [ ["in", "destination", ["::SOAP::SOAPString"]],
        ["retval", "dummy", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "unBlockDirtParaphrase"),
      "unBlockDirtParaphrase",
      "unBlockDirtParaphrase",
      [ ["in", "dirtParaphrase", ["::SOAP::SOAPString"]],
        ["retval", "dummy", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getCheckpointedGraph"),
      "getCheckpointedGraph",
      "getCheckpointedGraph",
      [ ["in", "rootIndividual", ["::SOAP::SOAPQName"]],
        ["retval", "conceptMap", ["ConceptMap", "urn:auraUserData", "ConceptMap"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "getSmeConceptDependencies"),
      "getSmeConceptDependencies",
      "getSmeConceptDependencies",
      [ ["in", "concept", ["::SOAP::SOAPQName"]],
        ["retval", "subclasses", ["QNameArray", "urn:auraUserData", "QNameArray"]],
        ["out", "referrers", ["QNameArray", "urn:auraUserData", "QNameArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "endQASession"),
      "endQASession",
      "endQASession",
      [ ["in", "dummy", ["::SOAP::SOAPString"]],
        ["retval", "dummy", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "lastDirtParaphrasesUsed"),
      "lastDirtParaphrasesUsed",
      "lastDirtParaphrasesUsed",
      [ ["in", "dummy", ["::SOAP::SOAPString"]],
        ["retval", "listOfDirtParaphrasesUsed", ["ArrayOfDirtParaphrases", "urn:auraUserData", "ArrayOfDirtParaphrases"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "resetQASession"),
      "resetQASession",
      "resetQASession",
      [ ["in", "dummy", ["::SOAP::SOAPString"]],
        ["retval", "dummy", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsAuraUserData, "extractConceptsFromText"),
      "extractConceptsFromText",
      "extractConceptsFromText",
      [ ["in", "textbooktext", ["::SOAP::SOAPString"]],
        ["retval", "vocabulary", ["VocabularyArray", "urn:auraUserData", "VocabularyArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = DefaultMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = DefaultMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

