#!/usr/bin/env ruby
if ARGV.any? {|arg| %w[--drb -X --generate-options -G --help -h --version -v].include?(arg)}
  require 'rubygems' unless ENV['NO_RUBYGEMS']
else
  gem 'test-unit', '1.2.3' if RUBY_VERSION.to_f >= 1.9
  ENV["RAILS_ENV"] ||= 'test'
end

require 'rubygems'
require 'spec'
exit ::Spec::Runner::CommandLine.run
